### ISSUE TITLE
Cloud data is not available on the first request using GameKit

### ISSUE THREAD

**Issue by YHSX88** [StansAssets/com.stansassets.ios-native#38]
Using Unity 2019.2.21f1 and not the latest Native IOS PRO

Issue is this:
**1. In Start function I'm setting ISN_GKLocalPlayer.FetchSavedGames (bear in mind that the user is authenticated by then -> check xcode logs.) Function returns no results.**

`private void Start()
    {
 
        // Auth the user
        if (Application.internetReachability != NetworkReachability.NotReachable)
        {
            //ISN_Preloader.LockScreen();
            if (ISN_GKLocalPlayer.LocalPlayer.Authenticated == false)
            {
                ISN_GKLocalPlayer.Authenticate(result =>
                {
                    if (result.IsSucceeded == true)
                    {
                        Debug.Log("User is authenticated: " + result.IsSucceeded);
                        ISN_GKLocalPlayer.FetchSavedGames((ISN_GKSavedGameFetchResult resulty) =>
                        {
                            Debug.Log("Cloud Level Count: 2222 " + resulty.SavedGames.Count.ToString());
                            if (resulty.IsSucceeded)
                            {
                                string svGames1 = "Checking Cloud Games Details_____" + "\r\n";
                                foreach (ISN_GKSavedGame game in resulty.SavedGames)
                                {
                                    svGames1 += "SaveGame Device Name: " + game.DeviceName + "\r\n";
                                    svGames1 += "SaveGame ID: " + game.Id + "\r\n";
                                    svGames1 += "SaveGame Name: " + game.Name + "\r\n";
                                    svGames1 += "SaveGame Modification Date: " + game.ModificationDate.ToLongDateString() + "\r\n";
                                    svGames1 += "---------------------------\r\n";
                                    Debug.Log(svGames1);
                                }
                            }
                        });
                    }
                    else
                    {
                        Debug.Log("User is NOT authenticated: " + result.IsFailed);
                        //ISN_Preloader.UnlockScreen();
                        //Show pop-up to log in to GameManager
                    }
 
                });
            }
            else
            {
 
            }
        }
 
    }`

**2. When I click on UI button using the function below I get 1 cloud save.**
`public void CloudSaveGamesCounts()
  {
        ISN_GKLocalPlayer.FetchSavedGames((ISN_GKSavedGameFetchResult result) =>
        {
            Debug.Log("Cloud Level Count:" + result.SavedGames.Count.ToString());
            if (result.IsSucceeded)
            {
                string svGames1 = "Checking Cloud Games Details_____" + "\r\n";
                foreach (ISN_GKSavedGame game in result.SavedGames)
                {
                    svGames1 += "SaveGame Device Name:" + game.DeviceName + "\r\n";
                    svGames1 += "SaveGame ID:" + game.Id + "\r\n";
                    svGames1 += "SaveGame Name:" + game.Name + "\r\n";
                    svGames1 += "SaveGame Modification Date:" + game.ModificationDate.ToLongDateString() + "\r\n";
                    svGames1 += "---------------------------\r\n";
                    Debug.Log(svGames1);
                }
            }
        });
    }`

3. I can also see the save cloud on the first time when I do the follow
3.1. Build and deploy app to phone via XCode
3.2. Press stop button in XCODE (don't delete the app on you phone that you just deployed)
3.3. Press Play button again in XCODE 
3.4 Cloud Save is found

Logs from XCODE for case 1
[Initial_Play.txt](https://github.com/StansAssets/com.stansassets.ios-native/files/4503776/Initial_Load.txt)

Logs from XCODE for case 2
[using_UI_Button.txt](https://github.com/StansAssets/com.stansassets.ios-native/files/4503777/using_UI_Button.txt)

Logs from XCODE for case 3 (i.e second run of XCODE)
[Second_Play.txt](https://github.com/StansAssets/com.stansassets.ios-native/files/4503778/SecondPlay.txt)

**Comment by stan-osipov** [comment]
Thx for the detailed description will look into it this week!

**Comment by stan-osipov** [comment]
I wasn't able to reproduce this on my devices. 
It seems to work just fine.  But analyzing your description I can suggest introducing a small delay before requesting the saved games data.
I know this is just a workaround and not really stable one, but the log you provided contains a legit response from the apple API with empty game list. Not much we can do at this point.

**Comment by stan-osipov** [comment]
One more small note regarding the `SN_GKLocalPlayer.Authenticate`. It is deprecated code, please consider using the [SetAuthenticateHandler](https://api.stansassets.com/ios-native/SA.iOS.GameKit.ISN_GKLocalPlayer.html#SA_iOS_GameKit_ISN_GKLocalPlayer_SetAuthenticateHandler_Action_SA_Result__) instead.

**Comment by YHSX88** [comment]
I replace it with SetAuthenticateHandler but still the same.

**Comment by stan-osipov** [comment]
I am not saying replacing with `SetAuthenticateHandler` would solve and issue, it's just the right thing to do overall.
There are no issues on a plugin side in a way how it fetches the saved games. I have few customers with the same problem that was able to fix it by introducing a small delay before requesting saved games data after user auth.

Sorry but can't give any better suggestions atm
