### ISSUE TITLE
ISN_NSNotificationCenter with MediaPlayer hangs in Xcode Simulator

### ISSUE THREAD

**Issue by JasonTdot** [StansAssets/com.stansassets.ios-native#39]
_ISN_NSNotificationCenter_AddObserverForName data: MPMusicPlayerControllerNowPlayingItemDidChangeNotification

<img width="1245" alt="Screen Shot 2020-04-21 at 3 23 09 PM" src="https://user-images.githubusercontent.com/51761268/79919592-aca96000-83fc-11ea-8d40-ad949b682d2d.png">

**Comment by stan-osipov** [comment]
Thanks for the report, it wasn't a simulator only issue. There was a type in function return type declaration on the C# part. 

The issue is fixed and will be available with `2020.5` release.

**Comment by JasonTdot** [comment]
Hi Stan, Just wondering if 2020.5 almost ready for release? If not, would I be able to just the script that needs correcting?




___
Jason Tan csc
+1.416.452.4922
+1.310.341.4150
www.jasontan.com
