### ISSUE TITLE
Request for Cloudkit implementation

### ISSUE THREAD

**Issue by kure-kung** [StansAssets/com.stansassets.ios-native#41]
Would like to have Cloudkit implementation as well
here are the min API that I being using in the project via another plugin, thanks

```
// containerIdentifier = iCloud Container Name
bool SelectDatabase ( bool usePrivateDatabase, string containerIdentifier = null )

// recordType = database name
// recordId = row's id
// title = file name
// content = file content, string
void SaveRecord ( string recordType, string recordId, string title, string content, Action<RecordInfo> result);
void FetchRecord ( string recordType, string recordId, Action<RecordInfo> result );
void UpdateRecord ( string recordType, string recordId, string title, string content, Action<RecordInfo> result );
void DeleteRecord ( string recordId, Action<RecordInfo> result );
```

**Comment by stan-osipov** [comment]
Thx for the request will look into it.

**Comment by stan-osipov** [comment]
Implemented:
* [CloudKit Overview
](https://github.com/StansAssets/com.stansassets.ios-native/wiki/CloudKit-Overview)
* [CouldKit save, fetch and delete records.](https://github.com/StansAssets/com.stansassets.ios-native/wiki/CouldKit---save,-fetch-and-delete-records.)
* [CloudKit creating records.](https://github.com/StansAssets/com.stansassets.ios-native/wiki/CloudKit-creating-records.)
