### ISSUE TITLE
Stray tap events with ISN_UIWheelPickerController

### ISSUE THREAD

**Issue by fhickman** [StansAssets/com.stansassets.ios-native#42]
When showing an ISN_UIWheelPickerController, it seems that the flexible space in between the “Done” and “Cancel” buttons (the ‘flex’ UIBarButtonItem instance) permits touch events to pass through it, and to be processed by the Unity View. This results in some undesired behavior, as the user can accidentally interact with other form elements when the WheelPicker is in view.

**Comment by stan-osipov** [comment]
Thx for the report. The issue is fixed and will be available with `2020.6` plugin update.
