### ISSUE TITLE
Implement casting via AirPlay(AppleTV) & Google Cast(Chromecast)

### ISSUE THREAD

**Issue by YHSX88** [StansAssets/com.stansassets.ios-native#43]
Hi, I want to ask if this nativePro plugin has the option to implement AirPlay to AppleTV. So that my users can cast gameplay to TV via AppleTV ?
And also to add to the previous comment of mine..... There is iOS plugin made by Google for Google Cast to Chromecast devices (https://developers.google.com/cast/docs/developers) if you can port this into iOS Native Pro (btw I know you can :D ).... you gonna kill it, as currently there is no single asset that is doing this ... and I'm getting the feeling would be quite nice to have feature. The one that is in asset store is deprecated by google for sure.

**Comment by stan-osipov** [comment]
Looks like Unity does have the support for AirPlay already, so I am not sure what kind of native API is expected.
Please feel free to reopen the issue if you will have more details.
