### ISSUE TITLE
[FEATURE REQUEST][GameCenter for iOS 14] Ability to control access point

### ISSUE THREAD

**Issue by DanielZ15** [StansAssets/com.stansassets.ios-native#46]
Ability to control GameCenter Access Point, otherwise the access point overlay will continuously be on screen(!). Adding this by request of Stan from here:
https://forum.unity.com/threads/released-ultimate-mobile-pro.571465/page-12#post-6096228

Documentation is here:
https://developer.apple.com/documentation/gamekit/gkaccesspoint
https://developer.apple.com/videos/play/wwdc2020/10145/

Thank you!

**Comment by vincentborcard** [comment]
Same request here.
Best!

**Comment by stan-osipov** [comment]
@DanielZ15 , @vincentborcard - done.
https://github.com/StansAssets/com.stansassets.ios-native/wiki/GK-Access-Point

The feature will be available with 2021.2.
If you want to get your hands on it earlier feel free to reach out for a beta version.
