### ISSUE TITLE
[FEATURE REQUEST] CarPlay?

### ISSUE THREAD

**Issue by JasonTdot** [StansAssets/com.stansassets.ios-native#48]
Is it possible to add support for CarPlay?

**Comment by stan-osipov** [comment]
Interesting idea, I will look into it :)

**Comment by stan-osipov** [comment]
I don't think it makes sense so far. Here is what quick research game me.
First of all only certain apps get entitlement for the car play:
* Messaging Apps
* Music Apps
* Automater Apps.

More about that is here:
https://developer.apple.com/videos/play/wwdc2017/719/

Plus I am not sure what native plugin can do there (apart from providing access to the iOS-specific API, which it already does)
You will have to build your Car play widget yourself without using any Unity API anyway.

**Comment by JasonTdot** [comment]
Yes, I see. I guess I was hoping there was a way to access the CarPlay interface to simply display information from the app. For my case I have made an app that mixes generated audio with playing audio media, so I just need away to start/stop the audio session and show feedback.  But yeah the entitlements might be too restrictive to do this.  I will keep looking.

**Comment by JasonTdot** [comment]
Btw, if you think your company can implement this custom functionality, it would be great if you could quote an estimated fee I could consider?
