### ISSUE TITLE
Location based notifications

### ISSUE THREAD

**Issue by DmytroSobko** [StansAssets/com.stansassets.ios-native#50]
Hey guys!

Is it possible to use it to start a process that will track the coordinates of the user's device, and if it is near one of the specific locations so that the application sends a local push notification?

I see this page in the documentation
https://api.stansassets.com/ios-native/SA.iOS.UserNotifications.ISN_UNLocationNotificationTrigger.html

Will this work out for our purposes?

And if possible, can you give an example code on how to use this API?
Or I can use these examples?
https://github.com/StansAssets/com.stansassets.ios-native/wiki/Scheduling-Notifications

Also is there a similar functionality for Android?

**Comment by stan-osipov** [comment]
We do not support the location trigger at the moment.
The main reason for this is that the unity player would not be able to accept a callback when the application is in the background mode.

Even if the application has permission to run in the background, the unity player is paused anyway when sent to the system background.
So the best way here is to make a native plugin that will cat like a background service and will contain your application business logic in regards to location-based notifications.
