### ISSUE TITLE
Ability to ask for AppTrackingTransparency permission in IOS14+

### ISSUE THREAD

**Issue by smaras** [StansAssets/com.stansassets.ios-native#51]
As requested here [https://forum.unity.com/threads/released-ultimate-mobile-pro.571465/page-14#post-6344595](url) here is my feature request.

**Reason:**
Apple is getting ready to enforce developers to ask for permission to use users IDFA for personalized ads via ApptrackingTransparency framework.

**Documentation**
Here is the official documentation
[https://developer.apple.com/documentation/apptrackingtransparency?language=objc](url) 

And here is an implementation guide from google admob docs.
[https://developers.google.com/admob/ios/ios14](url)

I would appreciate it if this feature made available in the plugin.

**Comment by stan-osipov** [comment]
Done :) 

The [ISN_ATTrackingManager](https://api.stansassets.com/ios-native/SA.iOS.AppTrackingTransparency.ISN_ATTrackingManager.html) is a mirrored class of the [ATTrackingManager](https://developer.apple.com/documentation/apptrackingtransparency/attrackingmanager) it provides a tracking authorization request and the tracking authorization status of the app.


Use the **AppTrackingTransparency** framework if your app collects data about end-users and shares it with other companies for purposes of tracking across apps and web sites. The AppTrackingTransparency framework presents an app-tracking authorization request to the user and provides the tracking authorization status.

1. Enabled App Tracking Transparency framework support
<img width="576" alt="UM_Welcome_-_NativePluginsUnityProject_-_iOS_-_Unity_2019_4_11f1__Metal_" src="https://user-images.githubusercontent.com/12031497/98602085-94415a00-22e8-11eb-84f2-983d1c1cd72d.png">

2. Set up a `NSUserTrackingUsageDescription` to display a system-permission alert request for your app installed on end-user devices.
<img width="573" alt="UM_Welcome_-_NativePluginsUnityProject_-_iOS_-_Unity_2019_4_11f1__Metal_" src="https://user-images.githubusercontent.com/12031497/98602182-baff9080-22e8-11eb-8bf7-573ae5ec8d46.png">

3. Call `RequestTrackingAuthorization` to present the app-tracking authorization request to the end-user.

```csharp
using SA.iOS.AppTrackingTransparency;
...

ISN_ATTrackingManager.RequestTrackingAuthorization(status =>
{
    Debug.Log($"New authorization status: {status}");
    UM_DialogsUtility.ShowNotification(status.ToString());
});
```

4. Use `TrackingAuthorizationStatus` to determine the app-tracking permission status. See [ISN_ATTrackingManager.AuthorizationStatus](https://api.stansassets.com/ios-native/SA.iOS.AppTrackingTransparency.ISN_ATTrackingManager.AuthorizationStatus.html) for status enums.

```csharp
using SA.iOS.AppTrackingTransparency;
...

Debug.Log($"Current authorization status: {ISN_ATTrackingManager.TrackingAuthorizationStatus}");
```
