### ISSUE TITLE
Fetching Contacts In IOS 14: Caveats

### ISSUE THREAD

**Issue by chris-o3h** [StansAssets/com.stansassets.ios-native#52]
I've found two caveats to the Contacts:

1. Including the notes field requires an entitlement since IOS 13. It probably should not be included by default as it throws an error.
2. If you sign in to an IOS device that has 0 contacts and populate the contacts from the cloud, this code will still report 9 contacts. Only if you add contacts manually in the contacts app will they show up.

Are you considering an update where the note field is not requested? For example modifying _ISN_Contacts.mm_:
`                NSArray *keys = @[CNContactGivenNameKey,CNContactFamilyNameKey, CNContactNicknameKey, CNContactOrganizationNameKey, CNContactDepartmentNameKey, CNContactJobTitleKey, CNContactEmailAddressesKey, CNContactPhoneNumbersKey];`

(And also removing all references to the note field in the respective classes).

Thoughts?

Thanks, great documentation and implementations!

**Comment by chris-o3h** [comment]
@stan-osipov Any thoughts on this? Thanks.

**Comment by stan-osipov** [comment]
Hey @chris-o3h yes that totally makes sense. The `note` field was added as part of the feature request.
It should definitely be configurable if it requires entitlement.

So as the user you can decide if you want to add a `note` request or not.

>If you sign in to an IOS device that has 0 contacts and populate the contacts from the cloud, this code will still report 9 contacts. Only if you add contacts manually in the contacts app will they show up.

Sorry not sure what do you mean. So the code will still return 9 contacts even if those are iCloud contacts. That seems like a good thing. Or am I missing something?

**Comment by chris-o3h** [comment]
Hi Stan,
Thanks for the response. 

For #2 I see I had a typo! What it should have said was:

..
If you sign in to an IOS device that has 0 contacts and populate the contacts from the cloud, this code will still report _**0 contacts**_. Only if you add contacts manually in the contacts app will they show up.
..

I'll have to verify this as I imported my personal contacts on a test iPhone while trying out the contacts feature of your plugin. It was reporting 0 contacts for several hours until I added a contact directly on the device. I'll know more when I get back to a related task later this week. 

Cheers.

[Update]
@stan-osipov I've confirmed. On this device where I imported all my contacts I only get the one contact I added manually. The others are missing.

Steps to reproduce:
* iPhone with IOS 14
* Ensure not signed in or signed in with an account with 0 contacts
* Sign into the device and import all contacts with an existing Apple ID account (should ask you to import)
* Open contacts app and not all contacts shown
* Add a new contact, call it whatever you like e.g. "Test Test"
* Run unity app using ios native plugin and list contacts
* Note that only the contact named "Test Test" shows in the list

**Comment by chris-o3h** [comment]
@stan-osipov Fix for reading all contacts:

Replace:
```
                NSString *containerId = store.defaultContainerIdentifier;
                NSPredicate *predicate = [CNContact predicateForContactsInContainerWithIdentifier:containerId];
```
With:
```
                // Setting the predicate to nil means "all"
                NSPredicate *predicate = nil;  
```

In ISN_Contacts.mm
Tested in IOS 14.1

**Comment by stan-osipov** [comment]
Thx @chris-o3h I will definitely test it and will include in the next update!

**Comment by stan-osipov** [comment]
Done:
https://github.com/StansAssets/com.stansassets.ios-native/wiki/Contacts-Store#notes-field

Thx again @chris-o3h
