### ISSUE TITLE
Feature request: UNNotificationServiceExtension implementation

### ISSUE THREAD

**Issue by chris-o3h** [StansAssets/com.stansassets.ios-native#56]
We are using remote push notifications with our app and including an image as part of the payload. However Apple's documentation states that you must implement the `UNNotificationServiceExtension`.

Any chance Stan's Asset's will be supporting this?
Thanks!

**Comment by stan-osipov** [comment]
I will look into it. I Will try to give you a reply by the end of the next week.

**Comment by chris-o3h** [comment]
Awesome! Thanks for letting us know.

**Comment by stan-osipov** [comment]
I looked into it a bit. 
According to the doc `UNNotificationServiceExtension ` lets you catch the `UNNotificationRequest ` object before it will be displayed for a user & modify its content.


A good example, if the `userInfo` contains `ENCRYPTED_DATA` filed then display message body as `"(Encrypted)"`. Here is the example code provided by Apple:

```swift
 let encryptedData = bestAttemptContent?.userInfo["ENCRYPTED_DATA"]
   if let bestAttemptContent = bestAttemptContent {
      if let data = encryptedData as? String {
         let decryptedMessage = self.decrypt(data: data)
        bestAttemptContent.body = decryptedMessage
      }
      else {
         bestAttemptContent.body = "(Encrypted)"
      }
      
      // Always call the completion handler when done.      
      contentHandler(bestAttemptContent)
   }
```

The thing is even tho it's possible to send the callback to the Unity C# and return the modified object back to the native code & make a nice C# API for that, but Unity C# part will only be able to receive this call back while running and in the foreground, which makes no sense to implement something like this.
