### ISSUE TITLE
SKPaymentDiscount_initWithIdentifier report

### ISSUE THREAD

**Issue by stan-osipov** [StansAssets/com.stansassets.ios-native#66]
In this function:

unsigned long _SKPaymentDiscount_initWithIdentifier(char identifier, char keyIdentifier, char nonce, char signature, unsigned long timestamp)

You make this call:
 
           SKPaymentDiscount *paymentDiscount = [[SKPaymentDiscount alloc] initWithIdentifier:[NSString stringWithUTF8String: identifier] keyIdentifier:[NSString stringWithUTF8String: identifier] nonce:uuid signature:[NSString stringWithUTF8String: identifier] timestamp:numberValue];

It looks to me like keyIdentifer and signature are being initialised with identifier. Looks like a copy and paste bug.

We couldn't get it working and then I spotted it and changed it to this:

                  SKPaymentDiscount *paymentDiscount = [[SKPaymentDiscount alloc] initWithIdentifier:[NSString stringWithUTF8String: identifier] keyIdentifier:[NSString stringWithUTF8String: keyIdentifier] nonce:uuid signature:[NSString stringWithUTF8String: signature] timestamp:numberValue];

Now it works.

**Comment by foritari** [comment]
Fixed.
