### ISSUE TITLE
Accumulation Bug list from Sarah Tan 

### ISSUE THREAD

**Issue by stan-osipov** [StansAssets/com.stansassets.ios-native#67]
- [x] **dding .tbd files is broken**

ISD_PostProcess.AddLibraries calls AddFrameworkToProject (line 390), which is only for .framework files. Use AddFileToBuild instead: proj.AddFileToBuild(targetGuid, proj.AddFile($"usr/lib/{lib.Name}", $"Frameworks/{lib.Name}", PBXSourceTree.Sdk));
Also on line 49 where AddLibraries is called, targetGuid should be replaced with frameworkTargetGuid.

- [x] **A lot of frameworks are missing from the ISD_iOSFramework enum**
They must be added to the end of the enum so existing settings don't get broken.

- [x] **ISN_CNContactsEditorResponse.txt is formatted incorrectly**
All the fields in m_Contacts should be capitalized, e.g. m_Contacts instead of m_contacts.

- [x] **k_IOSNativeApi path in ISN_Settings is wrong**
It should be IOSNativeFolder + "Runtime/API/"

- [x] **Enabling contacts permissions causes a hard crash with a CNPropertyNotFetchedException**
ISN_CNCommunication.m line 31 tries to access contact.note without checking if the note property was fetched, which by default is not.

- [x] **PushNotification trigger type is always being deserialized as Location trigger type**
We didn't test anything else or fix this one since we're not using it, but just want to mention it.

**Comment by foritari** [comment]
PushNotification trigger type is always being deserialized as Location trigger type - checked this one, and it worked as it should.
